//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int id_measurement { get; set; }
        public System.DateTime sample_time { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
        public Nullable<int> device_id { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<double> humidity { get; set; }
        public Nullable<double> pressure { get; set; }
    }
}
