//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampledImage
    {
        public int id_images { get; set; }
        public int device_id { get; set; }
        public System.DateTime image_timestamp { get; set; }
        public byte[] imagesample { get; set; }
    }
}
